spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    # InMemory
    url: jdbc:h2:mem:users
    username: sa
    password:
  h2.console.enabled: true
